name: Build Windows Application

on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan pemicuan manual

jobs:
  build:
    runs-on: windows-latest # Menggunakan runner Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET (jika menggunakan .NET)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Sesuaikan dengan versi .NET yang Anda gunakan

      - name: Install dependencies
        run: |
          dotnet restore # Menginstal dependensi

      - name: Build project
        run: |
          dotnet build --configuration Release # Mengkompilasi proyek

      - name: Run tests
        run: |
          dotnet test # Menjalankan pengujian

      - name: Package Application
        run: |
          dotnet publish --configuration Release --output ./output # Menghasilkan binari untuk produksi
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-application
          path: ./output # Menyimpan hasil build sebagai artefak
