name: Build and Create Tunnel with Ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan pemicuan manual

jobs:
  build:
    runs-on: windows-latest # Menggunakan runner Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET (jika menggunakan .NET)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Sesuaikan dengan versi .NET yang Anda gunakan

      - name: Install dependencies
        run: |
          dotnet restore # Menginstal dependensi

      - name: Build project
        run: |
          dotnet build --configuration Release # Mengkompilasi proyek

      - name: Run Application
        run: |
          Start-Process -NoNewWindow -FilePath "C:\path\to\your\application.exe" # Ganti dengan path aplikasi Anda
          Start-Sleep -s 10 # Tunggu beberapa detik agar aplikasi bisa berjalan

      - name: Download Ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/111111/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath Ngrok
          Remove-Item ngrok.zip

      - name: Start Ngrok Tunnel
        run: |
          Ngrok\ngrok.exe http 80 # Ganti dengan port yang diinginkan jika perlu
